# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59698d157cf58c112b01f04c70d7414f8cfba0ff6551d323a82d384c15ad0466e2c4825cbbe06c88bc43d476464f83c4c0c378d448e73db01a8197950c9ceaad

test:
  secret_key_base: 62515e53912a4da26b3b71c3337df539897b37ef8120e9c5233d1e5a7bc8b2fbe5e869f48648fa0acc9857623dc378174daa3dce136ddf39fb38ab4f382e6d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
